### ISSUE TITLE
build_oc.tool failled in Sequoia 15.7

### ISSUE THREAD

**Issue by chris1111** [acidanthera/bugtracker#2512]
build_oc.tool failled in Sequoia 15.7 with Xcode 16.4
- attaching full report log

[Terminal Saved Output.txt.zip](https://github.com/user-attachments/files/22046779/Terminal.Saved.Output.txt.zip)

Failled IA32 DEBUG with a long detail of the failure.

<img width="606" height="581" alt="Image" src="https://github.com/user-attachments/assets/88e5dce3-b030-4947-92d0-12320747b0dd" />

The end of failled

<img width="638" height="629" alt="Image" src="https://github.com/user-attachments/assets/65fe610e-500d-4ce9-9639-e21366750159" />

Thanks for help
I also try `build_duet.tool` then it pass without issue.
The only way I can build is using `ARCHS=(X64)`

**Comment by mikebeaton** [comment]
Xcode 16.4 works in general.

Your screenshot above doesn't show the actual error, which is in your attached log file however:

```
In file included from /Users/chris/Github/OpenCorePkg/UDK/OpenCorePkg/Library/OcCompressionLib/zlib/adler32.c:8:
/Users/chris/Github/OpenCorePkg/UDK/OpenCorePkg/Library/OcCompressionLib/zlib/zutil.h:170:11: error: 'OS_CODE' macro redefined [-Werror,-Wmacro-redefined]
  170 | #  define OS_CODE 19
      |           ^
/Users/chris/Github/OpenCorePkg/UDK/OpenCorePkg/Library/OcCompressionLib/zlib/zutil.h:141:11: note: previous definition is here
  141 | #  define OS_CODE  7
      |           ^
1 error generated.
```

It seems code around the mentioned lines is finding `__APPLE__` and `MACOS` defined, where that doesn't happen normally, but I am not sure why. (Suspect it is specific to something on your system; 16.4 on Tahoe works fine with no such problem for me, at least; and ~16.2 works in CI~ 16.4 in Sequoia is used for the current CI build.)

**Comment by mikebeaton** [comment]
MACOS refers to pre-Darwin Classic Mac OS, I don't know why it is defined for you. It shouldn't be!

**Comment by chris1111** [comment]
I am using Hackintosh iMac 20.1 AMD Radeon Pro WX 4100 4 GB

**Comment by mikebeaton** [comment]
Not a support forum. `MACOS` must have got set in your environment (compiler settings) somehow. Possibly you were trying to compile some very old code at some point? It is not being set by OC code.

Here is a recent CI build https://github.com/acidanthera/OpenCorePkg/actions/runs/17778620414/job/50532475368. Expand 'CI Bootstrap' to confirm that this is running on Sequoia Xcode 16.4; expand `build_duet` and `build_oc` to confirm that these worked fine.

**Comment by chris1111** [comment]
Test adding your patch in Tahoe 26 (25A354) latest
With Xcode 16.4 it work

here the output

[Terminal Saved Output.txt.zip](https://github.com/user-attachments/files/22383674/Terminal.Saved.Output.txt.zip)

I dont understand because I never have issue build OC tool 


EDIT **** Why Tahoe? because since i open this issue, Iam passing my main system to Tahoe 26
I have also Sequoia to another SSD

**Comment by chris1111** [comment]
Your patch now is included in the [Master source](https://github.com/acidanthera/OpenCorePkg/commit/849b04fdf42f5418f3fe4d4a46b0e297d3525d11)

**Comment by mikebeaton** [comment]
FYI I don't think the patch you are mentioning is anything to do with compilation failing (on your system?). But glad it is now working.

**Comment by mikebeaton** [comment]
I can confirm I have now seen [the error I got from your logs](https://github.com/acidanthera/bugtracker/issues/2512#issuecomment-3300418491) for myself. Sporadically, on Tahoe, on both Xcode 16.4 and 26.0. :-(

It appears to be related to `clang` defining `TARGET_OS_MAC` which is very weird as that should only be defined for Classic Mac OS (i.e. pre-OS X).
